name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.16'
      - name: Npm Install
        run: npm ci
        working-directory: ./
      # - name: Npm Install(Server)
      #   run: npm install
      #   working-directory: ./server
      - run: npm run build --prefix client
