name: GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
      - run: |
          cd client
          ls
