name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Install and Build Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          pwd
          npm install
        working-directory: ./client

      - name: Build
        run: |
          pwd
          npm run build
        working-directory: ./client

      - name: Install server dependencies
        run: |
          pwd
          npm install
        working-directory: ./server

      - name: Start server
        run: npm start
