name: GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  buld:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          npm run install
          npm run build --prefix client
